### ISSUE TITLE
What are the licenses on these CAD files? 

### ISSUE THREAD

**Issue by ismangil** [grbd/CAD.Solidworks.Parts#1]
I am designing an open source 3D printer adaptation, and I'd like to use these parts.

Thanks.

**Comment by Hecatron** [comment]
MIT free to use for anyone
I'll add in a licence file

just to mention though I made these for my own projects, so I can't guarantee the folder layout will stay the same in the future

**Comment by ismangil** [comment]
Great, thanks. The folder layout doesn't matter to me, I'm importing these into OnShape.
